site_name: KePrep
site_description: Minimally preprocessing TheBase dMRI data.
site_author: Gal Kepler

repo_url: https://github.com/GalKepler/keprep
edit_uri: https://github.com/GalKepler/keprep/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
