name: Codecov Report

on: [push, pull_request]

jobs:
  build:
    name: Run tests and upload coverage to Codecov
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install .  # Install your package

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    - name: Verify directory structure
      run: |
        echo "Verifying directory structure:"
        ls -R src/yalab_procedures

    - name: Display .coveragerc
      run: |
        echo "Displaying .coveragerc content:"
        cat .coveragerc

    - name: Run tests and collect coverage
      run: |
        mkdir -p reports
        pytest --cov-report term-missing:skip-covered --cov-report xml:reports/coverage.xml --cov-report html:reports/htmlcov --cov=src/yalab_procedures --cov-branch tests/ --verbose

    - name: Check coverage file
      run: |
        echo "Checking coverage file:"
        cat reports/coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: reports/coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
